---
# tasks file for roles/app
- name: Run BACKEND
  docker_container:
    name: backend
    image: bastienkatus/tpdockercomposercorrection_backend:latest
    networks: 
      - name: app-network
    ports:
      - 8080:8080

